/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package br.com.scheiner;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class EmployeeKey extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -2050876336705236212L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"EmployeeKey\",\"namespace\":\"br.com.scheiner\",\"fields\":[{\"name\":\"document\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<EmployeeKey> ENCODER =
      new BinaryMessageEncoder<EmployeeKey>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<EmployeeKey> DECODER =
      new BinaryMessageDecoder<EmployeeKey>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<EmployeeKey> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<EmployeeKey> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<EmployeeKey> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<EmployeeKey>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this EmployeeKey to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a EmployeeKey from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a EmployeeKey instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static EmployeeKey fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence document;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public EmployeeKey() {}

  /**
   * All-args constructor.
   * @param document The new value for document
   */
  public EmployeeKey(java.lang.CharSequence document) {
    this.document = document;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return document;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: document = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'document' field.
   * @return The value of the 'document' field.
   */
  public java.lang.CharSequence getDocument() {
    return document;
  }


  /**
   * Sets the value of the 'document' field.
   * @param value the value to set.
   */
  public void setDocument(java.lang.CharSequence value) {
    this.document = value;
  }

  /**
   * Creates a new EmployeeKey RecordBuilder.
   * @return A new EmployeeKey RecordBuilder
   */
  public static br.com.scheiner.EmployeeKey.Builder newBuilder() {
    return new br.com.scheiner.EmployeeKey.Builder();
  }

  /**
   * Creates a new EmployeeKey RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new EmployeeKey RecordBuilder
   */
  public static br.com.scheiner.EmployeeKey.Builder newBuilder(br.com.scheiner.EmployeeKey.Builder other) {
    if (other == null) {
      return new br.com.scheiner.EmployeeKey.Builder();
    } else {
      return new br.com.scheiner.EmployeeKey.Builder(other);
    }
  }

  /**
   * Creates a new EmployeeKey RecordBuilder by copying an existing EmployeeKey instance.
   * @param other The existing instance to copy.
   * @return A new EmployeeKey RecordBuilder
   */
  public static br.com.scheiner.EmployeeKey.Builder newBuilder(br.com.scheiner.EmployeeKey other) {
    if (other == null) {
      return new br.com.scheiner.EmployeeKey.Builder();
    } else {
      return new br.com.scheiner.EmployeeKey.Builder(other);
    }
  }

  /**
   * RecordBuilder for EmployeeKey instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<EmployeeKey>
    implements org.apache.avro.data.RecordBuilder<EmployeeKey> {

    private java.lang.CharSequence document;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(br.com.scheiner.EmployeeKey.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.document)) {
        this.document = data().deepCopy(fields()[0].schema(), other.document);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing EmployeeKey instance
     * @param other The existing instance to copy.
     */
    private Builder(br.com.scheiner.EmployeeKey other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.document)) {
        this.document = data().deepCopy(fields()[0].schema(), other.document);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'document' field.
      * @return The value.
      */
    public java.lang.CharSequence getDocument() {
      return document;
    }


    /**
      * Sets the value of the 'document' field.
      * @param value The value of 'document'.
      * @return This builder.
      */
    public br.com.scheiner.EmployeeKey.Builder setDocument(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.document = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'document' field has been set.
      * @return True if the 'document' field has been set, false otherwise.
      */
    public boolean hasDocument() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'document' field.
      * @return This builder.
      */
    public br.com.scheiner.EmployeeKey.Builder clearDocument() {
      document = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public EmployeeKey build() {
      try {
        EmployeeKey record = new EmployeeKey();
        record.document = fieldSetFlags()[0] ? this.document : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<EmployeeKey>
    WRITER$ = (org.apache.avro.io.DatumWriter<EmployeeKey>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<EmployeeKey>
    READER$ = (org.apache.avro.io.DatumReader<EmployeeKey>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.document);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.document = in.readString(this.document instanceof Utf8 ? (Utf8)this.document : null);

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.document = in.readString(this.document instanceof Utf8 ? (Utf8)this.document : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










